[tasks]
hello = "echo 'Hello from mise'"

[env]
_.file = ".env"
# _.path = ".node_modules/bin"
WORKSPACE = "{{env.HOME}}/w/"
SHELL = "/bin/zsh"

[tools]
go = "latest"
bun = "latest"
deno = "latest"
node = "latest"
python = "latest"
erlang = "latest"
elixir = "latest"
gleam = "latest"
rust = "latest"
zig = "latest"
fly = "latest"
usage = "latest"
watchexec = "latest"
